const translation = {
    es: {
        title: "CarConnect | Acceder",
        inicioregistro: "iniciar sesión",
        espanol: "Español",
        catalan: "Catalán",
        ingles: "Inglés",
        frances: "Francés",
        italiano: "Italiano",
        rumano: "Rumano",
        urdu: "Urdu",
        sueco: "Sueco",
        slogan: "Mensaje de coche a coche: la red social que tu coche estaba esperando.",
        CCh3: "Conexión Comunitaria",
        CCp: "Fomentamos una red de usuarios que se apoyan y ayudan entre ellos, manteniendo informados a los dueños de sus vehículos.",
        SAh3: "Seguridad Activa",
        SAp: "Nos preocupa la seguridad de los vehículos y sus propietarios, ayudándoles a tomar decisiones rápidas frente a incidentes.",
        RCh3: "Responsabilidad Compartida",
        RCp: "Promovemos una cultura de respeto y cuidado mutuo en la vía pública, haciendo que cada usuario contribuya a un entorno más seguro.",
        patrocinadores: "Patrocinadores",
        Celia: "Excelente servicio, muy rápido y fácil de usar. Me ayudaron a contactar con el propietario de un vehículo que estaba mal estacionado.",
        Eula: "Muy útil para notificar incidentes. Sería perfecto si permitiera añadir más detalles en los mensajes.",
        Marian: "Increíble herramienta, me ahorró mucho tiempo y el propietario respondió en pocos minutos.",
        Laura: "Funciona bien, pero mejoraría el diseño para hacerlo más intuitivo. Aun así, lo recomiendo.",
        Servicios: "Servicios",
        NIh5: "Notificación de Incidentes",
        NIp: "Envía alertas automáticas a los propietarios de los vehículos registrados cuando otros usuarios reportan incidentes como mal estacionamiento, daños, intentos de robo o situaciones peligrosas en la vía pública.",
        ISh5: "Integración con servicios de grúa y reparación",
        ISp: "Ofrece enlaces o convenios con servicios de grúa o talleres cercanos para facilitar la ayuda en casos de avería o accidentes.",
        RAh5: "Reporte Anónimo",
        RAp: "Permite a los usuarios realizar reportes anónimos de infracciones o daños, ideal para aquellos que prefieren notificar sin exponer su identidad, aunque esta opción requerirá cuenta para evitar falsas alarmas.",
        footerl1: "Inicio"
    },
    ca: {
        title: "CarConnect | Accedir",
        inicioregistro: "iniciar sessió",
        espanol: "Espanyol",
        catalan: "Català",
        ingles: "Anglès",
        frances: "Francès",
        italiano: "Italià",
        rumano: "Romanès",
        urdu: "Urdu",
        sueco: "Suec",
        slogan: "Missatge de cotxe a cotxe: la xarxa social que el teu cotxe estava esperant.",
        CCh3: "Connexió Comunitària",
        CCp: "Fomentem una xarxa d'usuaris que es recolzen i ajuden entre ells, mantenint informats als propietaris dels seus vehicles.",
        SAh3: "Seguretat Activa",
        SAp: "Ens preocupa la seguretat dels vehicles i els seus propietaris, ajudant-los a prendre decisions ràpides davant incidents.",
        RCh3: "Responsabilitat Compartida",
        RCp: "Promovem una cultura de respecte i cura mútua a la via pública, fent que cada usuari contribueixi a un entorn més segur.",
        patrocinadores: "Patrocinadors",
        Celia: "Excel·lent servei, molt ràpid i fàcil d'usar. Em van ajudar a contactar amb el propietari d'un vehicle que estava mal aparcat.",
        Eula: "Molt útil per notificar incidents. Seria perfecte si permetés afegir més detalls als missatges.",
        Marian: "Increïble eina, em va estalviar molt temps i el propietari va respondre en pocs minuts.",
        Laura: "Funciona bé, però milloraria el disseny per fer-lo més intuïtiu. Tot i així, el recomano.",
        Servicios: "Serveis",
        NIh5: "Notificació d'Incidents",
        NIp: "Envia alertes automàtiques als propietaris dels vehicles registrats quan altres usuaris informen d'incidents com mal aparcament, danys, intents de robatori o situacions perilloses a la via pública.",
        ISh5: "Integració amb serveis de grua i reparació",
        ISp: "Ofereix enllaços o convenis amb serveis de grua o tallers pròxims per facilitar l'ajuda en casos d'avaria o accidents.",
        RAh5: "Report Anònim",
        RAp: "Permet als usuaris fer informes anònims d'infraccions o danys, ideal per a aquells que prefereixen notificar sense exposar la seva identitat, tot i que aquesta opció requerirà compte per evitar falses alarmes.",
        footerl1: "Inici"
    },
    en: {
        "title": "CarConnect | Log In",
        "inicioregistro": "Log In",
        "espanol": "Spanish",
        "catalan": "Catalan",
        "ingles": "English",
        "frances": "French",
        "italiano": "Italian",
        "rumano": "Romanian",
        "urdu": "Urdu",
        "sueco": "Swedish",
        "slogan": "Car-to-car messaging: the social network your car was waiting for.",
        "CCh3": "Community Connection",
        "CCp": "We foster a network of users who support and help each other, keeping vehicle owners informed.",
        "SAh3": "Active Safety",
        "SAp": "We care about the safety of vehicles and their owners, helping them make quick decisions in case of incidents.",
        "RCh3": "Shared Responsibility",
        "RCp": "We promote a culture of mutual respect and care on public roads, encouraging each user to contribute to a safer environment.",
        "patrocinadores": "Sponsors",
        "Celia": "Excellent service, very fast and easy to use. They helped me contact the owner of a vehicle that was poorly parked.",
        "Eula": "Very useful for notifying incidents. It would be perfect if it allowed adding more details to the messages.",
        "Marian": "Incredible tool, saved me a lot of time, and the owner responded in just a few minutes.",
        "Laura": "Works well, but the design could be improved to make it more intuitive. Still, I recommend it.",
        "Servicios": "Services",
        "NIh5": "Incident Notification",
        "NIp": "Sends automatic alerts to registered vehicle owners when other users report incidents such as poor parking, damages, theft attempts, or dangerous situations on public roads.",
        "ISh5": "Integration with Towing and Repair Services",
        "ISp": "Provides links or agreements with nearby towing or repair services to assist in case of breakdowns or accidents.",
        "RAh5": "Anonymous Report",
        "RAp": "Allows users to make anonymous reports of violations or damages, ideal for those who prefer to notify without revealing their identity, although this option will require caution to avoid false alarms.",
        "footerl1": "Home"
    },
    fr: {
        "title": "CarConnect | Se connecter",
        "inicioregistro": "Se connecter",
        "espanol": "Espagnol",
        "catalan": "Catalan",
        "ingles": "Anglais",
        "frances": "Français",
        "italiano": "Italien",
        "rumano": "Roumain",
        "urdu": "Urdu",
        "sueco": "Suédois",
        "slogan": "Messagerie de voiture à voiture : le réseau social que votre voiture attendait.",
        "CCh3": "Connexion Communautaire",
        "CCp": "Nous favorisons un réseau d'utilisateurs qui se soutiennent et s'entraident, en maintenant les propriétaires de véhicules informés.",
        "SAh3": "Sécurité Active",
        "SAp": "Nous nous soucions de la sécurité des véhicules et de leurs propriétaires, en les aidant à prendre des décisions rapides en cas d'incidents.",
        "RCh3": "Responsabilité Partagée",
        "RCp": "Nous promouvons une culture de respect et de soin mutuels sur la voie publique, encourageant chaque utilisateur à contribuer à un environnement plus sûr.",
        "patrocinadores": "Sponsors",
        "Celia": "Service excellent, très rapide et facile à utiliser. Ils m'ont aidé à contacter le propriétaire d'un véhicule mal garé.",
        "Eula": "Très utile pour signaler des incidents. Ce serait parfait si l'on pouvait ajouter plus de détails aux messages.",
        "Marian": "Outil incroyable, m'a fait gagner beaucoup de temps et le propriétaire a répondu en quelques minutes.",
        "Laura": "Fonctionne bien, mais le design pourrait être amélioré pour le rendre plus intuitif. Malgré cela, je le recommande.",
        "Servicios": "Services",
        "NIh5": "Notification d'Incidents",
        "NIp": "Envoie des alertes automatiques aux propriétaires de véhicules enregistrés lorsqu'autres utilisateurs signalent des incidents tels que un mauvais stationnement, des dommages, des tentatives de vol ou des situations dangereuses sur la voie publique.",
        "ISh5": "Intégration avec des services de dépanneuse et de réparation",
        "ISp": "Propose des liens ou des accords avec des services de dépanneuse ou des ateliers proches pour faciliter l'aide en cas de panne ou d'accident.",
        "RAh5": "Rapport Anonyme",
        "RAp": "Permet aux utilisateurs de faire des rapports anonymes sur des violations ou des dommages, idéal pour ceux qui préfèrent signaler sans révéler leur identité, bien que cette option nécessite de la prudence pour éviter les fausses alarmes.",
        "footerl1": "Accueil"
    },
    it: {
        "title": "CarConnect | Accedi",
        "inicioregistro": "Accedi",
        "espanol": "Spagnolo",
        "catalan": "Catalano",
        "ingles": "Inglese",
        "frances": "Francese",
        "italiano": "Italiano",
        "rumano": "Romeno",
        "urdu": "Urdu",
        "sueco": "Svedese",
        "slogan": "Messaggio da auto a auto: la rete sociale che la tua auto stava aspettando.",
        "CCh3": "Connessione Comunitaria",
        "CCp": "Promuoviamo una rete di utenti che si supportano e si aiutano reciprocamente, mantenendo i proprietari dei veicoli informati.",
        "SAh3": "Sicurezza Attiva",
        "SAp": "Ci preoccupiamo della sicurezza dei veicoli e dei loro proprietari, aiutandoli a prendere decisioni rapide in caso di incidenti.",
        "RCh3": "Responsabilità Condivisa",
        "RCp": "Promuoviamo una cultura di rispetto e cura reciproca sulle strade pubbliche, incoraggiando ogni utente a contribuire a un ambiente più sicuro.",
        "patrocinadores": "Sponsor",
        "Celia": "Servizio eccellente, molto veloce e facile da usare. Mi hanno aiutato a contattare il proprietario di un veicolo mal parcheggiato.",
        "Eula": "Molto utile per segnalare incidenti. Sarebbe perfetto se fosse possibile aggiungere più dettagli ai messaggi.",
        "Marian": "Strumento incredibile, mi ha fatto risparmiare molto tempo e il proprietario ha risposto in pochi minuti.",
        "Laura": "Funziona bene, ma il design potrebbe essere migliorato per renderlo più intuitivo. Lo consiglio comunque.",
        "Servicios": "Servizi",
        "NIh5": "Notifica Incidenti",
        "NIp": "Invia avvisi automatici ai proprietari dei veicoli registrati quando altri utenti segnalano incidenti come parcheggio errato, danni, tentativi di furto o situazioni pericolose sulle strade pubbliche.",
        "ISh5": "Integrazione con servizi di carroattrezzi e riparazione",
        "ISp": "Offre link o accordi con servizi di carroattrezzi o officine vicine per facilitare l'aiuto in caso di guasti o incidenti.",
        "RAh5": "Segnalazione Anonima",
        "RAp": "Permette agli utenti di fare segnalazioni anonime di infrazioni o danni, ideale per chi preferisce notificare senza rivelare la propria identità, sebbene questa opzione richieda cautela per evitare falsi allarmi.",
        "footerl1": "Home"
    },
    ro: {
        "title": "CarConnect | Autentificare",
        "inicioregistro": "Autentificare",
        "espanol": "Spaniolă",
        "catalan": "Catalană",
        "ingles": "Engleză",
        "frances": "Franceză",
        "italiano": "Italiană",
        "rumano": "Română",
        "urdu": "Urdu",
        "sueco": "Suedeză",
        "slogan": "Mesaj de la mașină la mașină: rețeaua socială pe care mașina ta o aștepta.",
        "CCh3": "Conectare Comunitară",
        "CCp": "Promovăm o rețea de utilizatori care se sprijină și se ajută reciproc, menținându-i pe proprietarii de vehicule informați.",
        "SAh3": "Siguranță Activă",
        "SAp": "Ne pasă de siguranța vehiculelor și a proprietarilor acestora, ajutându-i să ia decizii rapide în caz de incidente.",
        "RCh3": "Responsabilitate Comună",
        "RCp": "Promovăm o cultură a respectului și îngrijirii reciproce pe drumurile publice, încurajând fiecare utilizator să contribuie la un mediu mai sigur.",
        "patrocinadores": "Sponsori",
        "Celia": "Serviciu excelent, foarte rapid și ușor de folosit. M-au ajutat să contactez proprietarul unui vehicul parcat incorect.",
        "Eula": "Foarte util pentru a semnala incidente. Ar fi perfect dacă ar permite adăugarea mai multor detalii în mesajele trimise.",
        "Marian": "Un instrument incredibil, mi-a economisit mult timp și proprietarul a răspuns în câteva minute.",
        "Laura": "Funcționează bine, dar designul ar putea fi îmbunătățit pentru a-l face mai intuitiv. Îl recomand totuși.",
        "Servicios": "Servicii",
        "NIh5": "Notificare Incidente",
        "NIp": "Trimite alerte automate proprietarilor de vehicule înregistrate atunci când alți utilizatori raportează incidente precum parcare incorectă, daune, tentative de furt sau situații periculoase pe drumurile publice.",
        "ISh5": "Integrare cu servicii de tractare și reparații",
        "ISp": "Oferă linkuri sau acorduri cu servicii de tractare sau ateliere din apropiere pentru a facilita ajutorul în caz de defecțiuni sau accidente.",
        "RAh5": "Raport Anonim",
        "RAp": "Permite utilizatorilor să facă rapoarte anonime despre încălcări sau daune, ideal pentru cei care preferă să semnaleze fără a-și dezvălui identitatea, deși această opțiune necesită precauție pentru a evita alarme false.",
        "footerl1": "Acasă"
    },
    ur: {
        "title": "CarConnect | لاگ ان",
        "inicioregistro": "لاگ ان",
        "espanol": "ہسپانوی",
        "catalan": "کیٹالان",
        "ingles": "انگریزی",
        "frances": "فرانسیسی",
        "italiano": "اطالوی",
        "rumano": "رومانی",
        "urdu": "اردو",
        "sueco": "سوئیڈش",
        "slogan": "کار سے کار پیغام رسانی: وہ سوشل نیٹ ورک جس کا آپ کی گاڑی کو انتظار تھا۔",
        "CCh3": "کمیونٹی کنکشن",
        "CCp": "ہم ایک ایسا نیٹ ورک تشکیل دیتے ہیں جہاں صارفین ایک دوسرے کی مدد کرتے ہیں اور گاڑی کے مالکان کو باخبر رکھتے ہیں۔",
        "SAh3": "فعال حفاظت",
        "SAp": "ہم گاڑیوں اور ان کے مالکان کی حفاظت کو ترجیح دیتے ہیں اور انہیں حادثات کی صورت میں فوری فیصلے کرنے میں مدد فراہم کرتے ہیں۔",
        "RCh3": "مشترکہ ذمہ داری",
        "RCp": "ہم عوامی سڑکوں پر باہمی احترام اور دیکھ بھال کی ثقافت کو فروغ دیتے ہیں، اور ہر صارف کو ایک محفوظ ماحول قائم کرنے میں حصہ ڈالنے کی ترغیب دیتے ہیں۔",
        "patrocinadores": "سرپرست",
        "Celia": "عمدہ سروس، بہت تیز اور استعمال میں آسان۔ انہوں نے میری مدد کی اور میں نے پارکنگ کے غلط مقام پر گاڑی کے مالک سے رابطہ کیا۔",
        "Eula": "واقعات کی اطلاع دینے کے لیے بہت مفید۔ یہ بہترین ہوتا اگر پیغامات میں مزید تفصیلات شامل کی جا سکتیں۔",
        "Marian": "لاجواب ٹول، اس نے مجھے بہت وقت بچایا اور مالک نے چند منٹوں میں جواب دیا۔",
        "Laura": "اچھی طرح سے کام کرتا ہے، لیکن ڈیزائن کو بہتر بنایا جا سکتا ہے تاکہ یہ زیادہ مفہوم ہو۔ پھر بھی میں اس کی سفارش کرتا ہوں۔",
        "Servicios": "خدمات",
        "NIh5": "واقعات کی اطلاع",
        "NIp": "جب دوسرے صارفین عوامی سڑکوں پر غلط پارکنگ، نقصانات، چوری کی کوششوں یا خطرناک حالات کی اطلاع دیتے ہیں تو یہ خودکار الرٹس رجسٹرڈ گاڑیوں کے مالکان کو بھیجتا ہے۔",
        "ISh5": "ٹروکنگ اور مرمت کی خدمات کے ساتھ انضمام",
        "ISp": "یہ قریبی ٹرکنگ یا ورکشاپ خدمات کے لنکس یا معاہدے فراہم کرتا ہے تاکہ خراب ہونے یا حادثات کی صورت میں مدد فراہم کی جا سکے۔",
        "RAh5": "گمنام رپورٹ",
        "RAp": "صارفین کو خلاف ورزیوں یا نقصانات کی گمنام اطلاع دینے کی اجازت دیتا ہے، جو ان لوگوں کے لیے مثالی ہے جو اپنی شناخت ظاہر کیے بغیر اطلاع دینا چاہتے ہیں، حالانکہ اس اختیار کو جھوٹی اطلاعات سے بچنے کے لیے محتاط استعمال کرنے کی ضرورت ہوگی۔",
        "footerl1": "گھر"
    },
    su: {
        "title": "CarConnect | Logga in",
        "inicioregistro": "Logga in",
        "espanol": "Spanska",
        "catalan": "Katalanska",
        "ingles": "Engelska",
        "frances": "Franska",
        "italiano": "Italienska",
        "rumano": "Rumänska",
        "urdu": "Urdu",
        "sueco": "Svenska",
        "slogan": "Bil till bil-meddelande: det sociala nätverket som din bil har väntat på.",
        "CCh3": "Gemenskapsanslutning",
        "CCp": "Vi främjar ett nätverk av användare som stöder och hjälper varandra, samtidigt som vi håller bilägare informerade.",
        "SAh3": "Aktiv säkerhet",
        "SAp": "Vi bryr oss om säkerheten för fordon och deras ägare, och hjälper dem att fatta snabba beslut vid incidenter.",
        "RCh3": "Delat ansvar",
        "RCp": "Vi främjar en kultur av ömsesidig respekt och omsorg på allmänna vägar, vilket uppmuntrar varje användare att bidra till en säkrare miljö.",
        "patrocinadores": "Sponsorer",
        "Celia": "Utmärkt service, mycket snabb och lätt att använda. De hjälpte mig att kontakta ägaren av ett felparkerat fordon.",
        "Eula": "Mycket användbart för att rapportera incidenter. Det skulle vara perfekt om man kunde lägga till fler detaljer i meddelandena.",
        "Marian": "Otrolig verktyg, sparade mig mycket tid och ägaren svarade på några minuter.",
        "Laura": "Fungerar bra, men designen skulle kunna förbättras för att göra den mer intuitiv. Jag rekommenderar det ändå.",
        "Servicios": "Tjänster",
        "NIh5": "Incidentrapportering",
        "NIp": "Skickar automatiska varningar till registrerade bilägare när andra användare rapporterar incidenter som felparkering, skador, stöldförsök eller farliga situationer på offentliga vägar.",
        "ISh5": "Integration med bärgnings- och reparationsservice",
        "ISp": "Erbjuder länkar eller avtal med närliggande bärgnings- eller verkstadstjänster för att underlätta hjälp vid driftstopp eller olyckor.",
        "RAh5": "Anonym rapport",
        "RAp": "Tillåter användare att göra anonyma rapporter om överträdelser eller skador, vilket är idealiskt för dem som föredrar att rapportera utan att avslöja sin identitet, men detta alternativ kräver försiktighet för att undvika falska larm.",
        "footerl1": "Hem"
    }         
};

// Idioma predeterminado
let currentLanguage = 'es'; // Valor predeterminado: español

// Función para cargar las traducciones y actualizar el contenido de la página
// Función para cargar las traducciones y actualizar el contenido de la página
function loadLanguage(language) {
    console.log("Cargando idioma: ", language); // Agregar log aquí
    // Verificar si el idioma existe en el objeto de traducciones
    if (translation[language]) {
        const translatableElements = document.querySelectorAll('[data-translate]');
        translatableElements.forEach(element => {
            const key = element.getAttribute('data-translate');
            const translatedText = translation[language][key];
            if (translatedText) {
                element.textContent = translatedText;
            }
        });
    }
}


// Event listener para cambiar el idioma
document.getElementById('lenguage').addEventListener('change', function (event) {
    currentLanguage = event.target.value; // Actualizar el idioma seleccionado
    loadLanguage(currentLanguage); // Aplicar las traducciones
});

// Cargar el idioma predeterminado al iniciar
loadLanguage(currentLanguage);
